# Generated by Django 2.0.13 on 2019-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
