# Generated by Django 2.0.13 on 2019-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroll', '0002_auto_20190703_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
