# Generated by Django 2.0.13 on 2019-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroll', '0003_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
