# Generated by Django 2.0.13 on 2019-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroll', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
